// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.1
// source: message.proto

package message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FeiShuService_WebFsAlarmPush_FullMethodName         = "/FeiShuService/WebFsAlarmPush"
	FeiShuService_FsAlarmPush_FullMethodName            = "/FeiShuService/FsAlarmPush"
	FeiShuService_WebFsAlarmRobotSet_FullMethodName     = "/FeiShuService/WebFsAlarmRobotSet"
	FeiShuService_WebFsAlarmRobotListGet_FullMethodName = "/FeiShuService/WebFsAlarmRobotListGet"
	FeiShuService_WebFsAlarmRobotDelete_FullMethodName  = "/FeiShuService/WebFsAlarmRobotDelete"
)

// FeiShuServiceClient is the client API for FeiShuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeiShuServiceClient interface {
	// 飞书告警消息转发
	WebFsAlarmPush(ctx context.Context, in *FsAlarmPushRequest, opts ...grpc.CallOption) (*FsAlarmPushResponse, error)
	// 飞书告警消息转发
	FsAlarmPush(ctx context.Context, in *FsAlarmPushRequest, opts ...grpc.CallOption) (*FsAlarmPushResponse, error)
	// 飞书告警机器人信息设置
	WebFsAlarmRobotSet(ctx context.Context, in *WebFsAlarmRobotSetRequest, opts ...grpc.CallOption) (*WebFsAlarmRobotSetResponse, error)
	// 飞书告警机器人信息列表获取
	WebFsAlarmRobotListGet(ctx context.Context, in *WebFsAlarmRobotListGetRequest, opts ...grpc.CallOption) (*WebFsAlarmRobotListGetResponse, error)
	// 飞书告警机器人信息删除
	WebFsAlarmRobotDelete(ctx context.Context, in *WebFsAlarmRobotDeleteRequest, opts ...grpc.CallOption) (*WebFsAlarmRobotDeleteResponse, error)
}

type feiShuServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFeiShuServiceClient(cc grpc.ClientConnInterface) FeiShuServiceClient {
	return &feiShuServiceClient{cc}
}

func (c *feiShuServiceClient) WebFsAlarmPush(ctx context.Context, in *FsAlarmPushRequest, opts ...grpc.CallOption) (*FsAlarmPushResponse, error) {
	out := new(FsAlarmPushResponse)
	err := c.cc.Invoke(ctx, FeiShuService_WebFsAlarmPush_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feiShuServiceClient) FsAlarmPush(ctx context.Context, in *FsAlarmPushRequest, opts ...grpc.CallOption) (*FsAlarmPushResponse, error) {
	out := new(FsAlarmPushResponse)
	err := c.cc.Invoke(ctx, FeiShuService_FsAlarmPush_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feiShuServiceClient) WebFsAlarmRobotSet(ctx context.Context, in *WebFsAlarmRobotSetRequest, opts ...grpc.CallOption) (*WebFsAlarmRobotSetResponse, error) {
	out := new(WebFsAlarmRobotSetResponse)
	err := c.cc.Invoke(ctx, FeiShuService_WebFsAlarmRobotSet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feiShuServiceClient) WebFsAlarmRobotListGet(ctx context.Context, in *WebFsAlarmRobotListGetRequest, opts ...grpc.CallOption) (*WebFsAlarmRobotListGetResponse, error) {
	out := new(WebFsAlarmRobotListGetResponse)
	err := c.cc.Invoke(ctx, FeiShuService_WebFsAlarmRobotListGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feiShuServiceClient) WebFsAlarmRobotDelete(ctx context.Context, in *WebFsAlarmRobotDeleteRequest, opts ...grpc.CallOption) (*WebFsAlarmRobotDeleteResponse, error) {
	out := new(WebFsAlarmRobotDeleteResponse)
	err := c.cc.Invoke(ctx, FeiShuService_WebFsAlarmRobotDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeiShuServiceServer is the server API for FeiShuService service.
// All implementations must embed UnimplementedFeiShuServiceServer
// for forward compatibility
type FeiShuServiceServer interface {
	// 飞书告警消息转发
	WebFsAlarmPush(context.Context, *FsAlarmPushRequest) (*FsAlarmPushResponse, error)
	// 飞书告警消息转发
	FsAlarmPush(context.Context, *FsAlarmPushRequest) (*FsAlarmPushResponse, error)
	// 飞书告警机器人信息设置
	WebFsAlarmRobotSet(context.Context, *WebFsAlarmRobotSetRequest) (*WebFsAlarmRobotSetResponse, error)
	// 飞书告警机器人信息列表获取
	WebFsAlarmRobotListGet(context.Context, *WebFsAlarmRobotListGetRequest) (*WebFsAlarmRobotListGetResponse, error)
	// 飞书告警机器人信息删除
	WebFsAlarmRobotDelete(context.Context, *WebFsAlarmRobotDeleteRequest) (*WebFsAlarmRobotDeleteResponse, error)
	mustEmbedUnimplementedFeiShuServiceServer()
}

// UnimplementedFeiShuServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFeiShuServiceServer struct {
}

func (UnimplementedFeiShuServiceServer) WebFsAlarmPush(context.Context, *FsAlarmPushRequest) (*FsAlarmPushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WebFsAlarmPush not implemented")
}
func (UnimplementedFeiShuServiceServer) FsAlarmPush(context.Context, *FsAlarmPushRequest) (*FsAlarmPushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FsAlarmPush not implemented")
}
func (UnimplementedFeiShuServiceServer) WebFsAlarmRobotSet(context.Context, *WebFsAlarmRobotSetRequest) (*WebFsAlarmRobotSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WebFsAlarmRobotSet not implemented")
}
func (UnimplementedFeiShuServiceServer) WebFsAlarmRobotListGet(context.Context, *WebFsAlarmRobotListGetRequest) (*WebFsAlarmRobotListGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WebFsAlarmRobotListGet not implemented")
}
func (UnimplementedFeiShuServiceServer) WebFsAlarmRobotDelete(context.Context, *WebFsAlarmRobotDeleteRequest) (*WebFsAlarmRobotDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WebFsAlarmRobotDelete not implemented")
}
func (UnimplementedFeiShuServiceServer) mustEmbedUnimplementedFeiShuServiceServer() {}

// UnsafeFeiShuServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeiShuServiceServer will
// result in compilation errors.
type UnsafeFeiShuServiceServer interface {
	mustEmbedUnimplementedFeiShuServiceServer()
}

func RegisterFeiShuServiceServer(s grpc.ServiceRegistrar, srv FeiShuServiceServer) {
	s.RegisterService(&FeiShuService_ServiceDesc, srv)
}

func _FeiShuService_WebFsAlarmPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FsAlarmPushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeiShuServiceServer).WebFsAlarmPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeiShuService_WebFsAlarmPush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeiShuServiceServer).WebFsAlarmPush(ctx, req.(*FsAlarmPushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeiShuService_FsAlarmPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FsAlarmPushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeiShuServiceServer).FsAlarmPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeiShuService_FsAlarmPush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeiShuServiceServer).FsAlarmPush(ctx, req.(*FsAlarmPushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeiShuService_WebFsAlarmRobotSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebFsAlarmRobotSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeiShuServiceServer).WebFsAlarmRobotSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeiShuService_WebFsAlarmRobotSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeiShuServiceServer).WebFsAlarmRobotSet(ctx, req.(*WebFsAlarmRobotSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeiShuService_WebFsAlarmRobotListGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebFsAlarmRobotListGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeiShuServiceServer).WebFsAlarmRobotListGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeiShuService_WebFsAlarmRobotListGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeiShuServiceServer).WebFsAlarmRobotListGet(ctx, req.(*WebFsAlarmRobotListGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeiShuService_WebFsAlarmRobotDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebFsAlarmRobotDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeiShuServiceServer).WebFsAlarmRobotDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeiShuService_WebFsAlarmRobotDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeiShuServiceServer).WebFsAlarmRobotDelete(ctx, req.(*WebFsAlarmRobotDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FeiShuService_ServiceDesc is the grpc.ServiceDesc for FeiShuService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeiShuService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FeiShuService",
	HandlerType: (*FeiShuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WebFsAlarmPush",
			Handler:    _FeiShuService_WebFsAlarmPush_Handler,
		},
		{
			MethodName: "FsAlarmPush",
			Handler:    _FeiShuService_FsAlarmPush_Handler,
		},
		{
			MethodName: "WebFsAlarmRobotSet",
			Handler:    _FeiShuService_WebFsAlarmRobotSet_Handler,
		},
		{
			MethodName: "WebFsAlarmRobotListGet",
			Handler:    _FeiShuService_WebFsAlarmRobotListGet_Handler,
		},
		{
			MethodName: "WebFsAlarmRobotDelete",
			Handler:    _FeiShuService_WebFsAlarmRobotDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}

const (
	PushService_PushInviteMessage_FullMethodName = "/PushService/PushInviteMessage"
)

// PushServiceClient is the client API for PushService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PushServiceClient interface {
	// 查询系统配置信息
	PushInviteMessage(ctx context.Context, in *PushInvitedMessageRequest, opts ...grpc.CallOption) (*PushInvitedMessageResponse, error)
}

type pushServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPushServiceClient(cc grpc.ClientConnInterface) PushServiceClient {
	return &pushServiceClient{cc}
}

func (c *pushServiceClient) PushInviteMessage(ctx context.Context, in *PushInvitedMessageRequest, opts ...grpc.CallOption) (*PushInvitedMessageResponse, error) {
	out := new(PushInvitedMessageResponse)
	err := c.cc.Invoke(ctx, PushService_PushInviteMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PushServiceServer is the server API for PushService service.
// All implementations must embed UnimplementedPushServiceServer
// for forward compatibility
type PushServiceServer interface {
	// 查询系统配置信息
	PushInviteMessage(context.Context, *PushInvitedMessageRequest) (*PushInvitedMessageResponse, error)
	mustEmbedUnimplementedPushServiceServer()
}

// UnimplementedPushServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPushServiceServer struct {
}

func (UnimplementedPushServiceServer) PushInviteMessage(context.Context, *PushInvitedMessageRequest) (*PushInvitedMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushInviteMessage not implemented")
}
func (UnimplementedPushServiceServer) mustEmbedUnimplementedPushServiceServer() {}

// UnsafePushServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushServiceServer will
// result in compilation errors.
type UnsafePushServiceServer interface {
	mustEmbedUnimplementedPushServiceServer()
}

func RegisterPushServiceServer(s grpc.ServiceRegistrar, srv PushServiceServer) {
	s.RegisterService(&PushService_ServiceDesc, srv)
}

func _PushService_PushInviteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushInvitedMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).PushInviteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushService_PushInviteMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).PushInviteMessage(ctx, req.(*PushInvitedMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PushService_ServiceDesc is the grpc.ServiceDesc for PushService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PushService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PushService",
	HandlerType: (*PushServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushInviteMessage",
			Handler:    _PushService_PushInviteMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}

const (
	PullService_PullProtoMessage1_FullMethodName = "/PullService/PullProtoMessage1"
	PullService_PullProtoMessage2_FullMethodName = "/PullService/PullProtoMessage2"
)

// PullServiceClient is the client API for PullService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PullServiceClient interface {
	PullProtoMessage1(ctx context.Context, in *PushInvitedMessageRequest, opts ...grpc.CallOption) (*PushInvitedMessageResponse, error)
	PullProtoMessage2(ctx context.Context, in *PushInvitedMessageRequest, opts ...grpc.CallOption) (*PushInvitedMessageResponse, error)
}

type pullServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPullServiceClient(cc grpc.ClientConnInterface) PullServiceClient {
	return &pullServiceClient{cc}
}

func (c *pullServiceClient) PullProtoMessage1(ctx context.Context, in *PushInvitedMessageRequest, opts ...grpc.CallOption) (*PushInvitedMessageResponse, error) {
	out := new(PushInvitedMessageResponse)
	err := c.cc.Invoke(ctx, PullService_PullProtoMessage1_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pullServiceClient) PullProtoMessage2(ctx context.Context, in *PushInvitedMessageRequest, opts ...grpc.CallOption) (*PushInvitedMessageResponse, error) {
	out := new(PushInvitedMessageResponse)
	err := c.cc.Invoke(ctx, PullService_PullProtoMessage2_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PullServiceServer is the server API for PullService service.
// All implementations must embed UnimplementedPullServiceServer
// for forward compatibility
type PullServiceServer interface {
	PullProtoMessage1(context.Context, *PushInvitedMessageRequest) (*PushInvitedMessageResponse, error)
	PullProtoMessage2(context.Context, *PushInvitedMessageRequest) (*PushInvitedMessageResponse, error)
	mustEmbedUnimplementedPullServiceServer()
}

// UnimplementedPullServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPullServiceServer struct {
}

func (UnimplementedPullServiceServer) PullProtoMessage1(context.Context, *PushInvitedMessageRequest) (*PushInvitedMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullProtoMessage1 not implemented")
}
func (UnimplementedPullServiceServer) PullProtoMessage2(context.Context, *PushInvitedMessageRequest) (*PushInvitedMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullProtoMessage2 not implemented")
}
func (UnimplementedPullServiceServer) mustEmbedUnimplementedPullServiceServer() {}

// UnsafePullServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PullServiceServer will
// result in compilation errors.
type UnsafePullServiceServer interface {
	mustEmbedUnimplementedPullServiceServer()
}

func RegisterPullServiceServer(s grpc.ServiceRegistrar, srv PullServiceServer) {
	s.RegisterService(&PullService_ServiceDesc, srv)
}

func _PullService_PullProtoMessage1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushInvitedMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PullServiceServer).PullProtoMessage1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PullService_PullProtoMessage1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PullServiceServer).PullProtoMessage1(ctx, req.(*PushInvitedMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PullService_PullProtoMessage2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushInvitedMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PullServiceServer).PullProtoMessage2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PullService_PullProtoMessage2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PullServiceServer).PullProtoMessage2(ctx, req.(*PushInvitedMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PullService_ServiceDesc is the grpc.ServiceDesc for PullService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PullService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PullService",
	HandlerType: (*PullServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PullProtoMessage1",
			Handler:    _PullService_PullProtoMessage1_Handler,
		},
		{
			MethodName: "PullProtoMessage2",
			Handler:    _PullService_PullProtoMessage2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}

const (
	FeiShuAlarmDB_AddFeiShuAlarmInfo_FullMethodName = "/FeiShuAlarmDB/AddFeiShuAlarmInfo"
	FeiShuAlarmDB_GetFeiShuAlarmInfo_FullMethodName = "/FeiShuAlarmDB/GetFeiShuAlarmInfo"
	FeiShuAlarmDB_DeleteAlarmInfo_FullMethodName    = "/FeiShuAlarmDB/DeleteAlarmInfo"
)

// FeiShuAlarmDBClient is the client API for FeiShuAlarmDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeiShuAlarmDBClient interface {
	// 添加告警组机器信息
	AddFeiShuAlarmInfo(ctx context.Context, in *AddFeiShuAlarmInfoDBRequest, opts ...grpc.CallOption) (*AddFeiShuAlarmInfoDBResponse, error)
	GetFeiShuAlarmInfo(ctx context.Context, in *GetFeiShuAlarmListDBRequest, opts ...grpc.CallOption) (*GetFeiShuAlarmListDBResponse, error)
	DeleteAlarmInfo(ctx context.Context, in *DeleteFeiShuAlarmInfoDBRequest, opts ...grpc.CallOption) (*DeleteFeiShuAlarmInfoDBResponse, error)
}

type feiShuAlarmDBClient struct {
	cc grpc.ClientConnInterface
}

func NewFeiShuAlarmDBClient(cc grpc.ClientConnInterface) FeiShuAlarmDBClient {
	return &feiShuAlarmDBClient{cc}
}

func (c *feiShuAlarmDBClient) AddFeiShuAlarmInfo(ctx context.Context, in *AddFeiShuAlarmInfoDBRequest, opts ...grpc.CallOption) (*AddFeiShuAlarmInfoDBResponse, error) {
	out := new(AddFeiShuAlarmInfoDBResponse)
	err := c.cc.Invoke(ctx, FeiShuAlarmDB_AddFeiShuAlarmInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feiShuAlarmDBClient) GetFeiShuAlarmInfo(ctx context.Context, in *GetFeiShuAlarmListDBRequest, opts ...grpc.CallOption) (*GetFeiShuAlarmListDBResponse, error) {
	out := new(GetFeiShuAlarmListDBResponse)
	err := c.cc.Invoke(ctx, FeiShuAlarmDB_GetFeiShuAlarmInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feiShuAlarmDBClient) DeleteAlarmInfo(ctx context.Context, in *DeleteFeiShuAlarmInfoDBRequest, opts ...grpc.CallOption) (*DeleteFeiShuAlarmInfoDBResponse, error) {
	out := new(DeleteFeiShuAlarmInfoDBResponse)
	err := c.cc.Invoke(ctx, FeiShuAlarmDB_DeleteAlarmInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeiShuAlarmDBServer is the server API for FeiShuAlarmDB service.
// All implementations must embed UnimplementedFeiShuAlarmDBServer
// for forward compatibility
type FeiShuAlarmDBServer interface {
	// 添加告警组机器信息
	AddFeiShuAlarmInfo(context.Context, *AddFeiShuAlarmInfoDBRequest) (*AddFeiShuAlarmInfoDBResponse, error)
	GetFeiShuAlarmInfo(context.Context, *GetFeiShuAlarmListDBRequest) (*GetFeiShuAlarmListDBResponse, error)
	DeleteAlarmInfo(context.Context, *DeleteFeiShuAlarmInfoDBRequest) (*DeleteFeiShuAlarmInfoDBResponse, error)
	mustEmbedUnimplementedFeiShuAlarmDBServer()
}

// UnimplementedFeiShuAlarmDBServer must be embedded to have forward compatible implementations.
type UnimplementedFeiShuAlarmDBServer struct {
}

func (UnimplementedFeiShuAlarmDBServer) AddFeiShuAlarmInfo(context.Context, *AddFeiShuAlarmInfoDBRequest) (*AddFeiShuAlarmInfoDBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFeiShuAlarmInfo not implemented")
}
func (UnimplementedFeiShuAlarmDBServer) GetFeiShuAlarmInfo(context.Context, *GetFeiShuAlarmListDBRequest) (*GetFeiShuAlarmListDBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeiShuAlarmInfo not implemented")
}
func (UnimplementedFeiShuAlarmDBServer) DeleteAlarmInfo(context.Context, *DeleteFeiShuAlarmInfoDBRequest) (*DeleteFeiShuAlarmInfoDBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAlarmInfo not implemented")
}
func (UnimplementedFeiShuAlarmDBServer) mustEmbedUnimplementedFeiShuAlarmDBServer() {}

// UnsafeFeiShuAlarmDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeiShuAlarmDBServer will
// result in compilation errors.
type UnsafeFeiShuAlarmDBServer interface {
	mustEmbedUnimplementedFeiShuAlarmDBServer()
}

func RegisterFeiShuAlarmDBServer(s grpc.ServiceRegistrar, srv FeiShuAlarmDBServer) {
	s.RegisterService(&FeiShuAlarmDB_ServiceDesc, srv)
}

func _FeiShuAlarmDB_AddFeiShuAlarmInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFeiShuAlarmInfoDBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeiShuAlarmDBServer).AddFeiShuAlarmInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeiShuAlarmDB_AddFeiShuAlarmInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeiShuAlarmDBServer).AddFeiShuAlarmInfo(ctx, req.(*AddFeiShuAlarmInfoDBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeiShuAlarmDB_GetFeiShuAlarmInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeiShuAlarmListDBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeiShuAlarmDBServer).GetFeiShuAlarmInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeiShuAlarmDB_GetFeiShuAlarmInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeiShuAlarmDBServer).GetFeiShuAlarmInfo(ctx, req.(*GetFeiShuAlarmListDBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeiShuAlarmDB_DeleteAlarmInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFeiShuAlarmInfoDBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeiShuAlarmDBServer).DeleteAlarmInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeiShuAlarmDB_DeleteAlarmInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeiShuAlarmDBServer).DeleteAlarmInfo(ctx, req.(*DeleteFeiShuAlarmInfoDBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FeiShuAlarmDB_ServiceDesc is the grpc.ServiceDesc for FeiShuAlarmDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeiShuAlarmDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FeiShuAlarmDB",
	HandlerType: (*FeiShuAlarmDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddFeiShuAlarmInfo",
			Handler:    _FeiShuAlarmDB_AddFeiShuAlarmInfo_Handler,
		},
		{
			MethodName: "GetFeiShuAlarmInfo",
			Handler:    _FeiShuAlarmDB_GetFeiShuAlarmInfo_Handler,
		},
		{
			MethodName: "DeleteAlarmInfo",
			Handler:    _FeiShuAlarmDB_DeleteAlarmInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
