version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8001:8001
      - 8002:8002
      - 8003:8003
    volumes:
      - D:\code\compose-config\html\nginx\www:/usr/share/nginx/html
      - D:\code\compose-config\html\nginx\conf\nginx.conf:/etc/nginx/nginx.conf
      - D:\code\compose-config\html\nginx\logs:/var/log/nginx nginx
      
  mysql:
    restart: always
    image: mysql:latest
    container_name: mysql
    volumes:
      - D:\code\compose-config\mysql\mydir:/mydir
      - D:\code\compose-config\mysql\datadir:/var/lib/mysql
      - D:\code\compose-config\mysql\source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=Starverse"
      - "TZ=Asia/Shanghai"
    ports:
       - 3306:3306
      
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - D:\code\compose-config\mongo:/data/db
      
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    privileged: true
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - D:\code\compose-config\mqtt\config:/mosquitto/config
      - D:\code\compose-config\mqtt\data:/mosquitto/data
      - D:\code\compose-config\mqtt\log:/mosquitto/log
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - D:\code\compose-config\prometheus:/etc/prometheus
      - D:\code\compose-config\prometheus/rules:/etc/prometheus/rules
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - D:\code\compose-config\prometheus\grafana:/var/lib/grafana
      
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: always
    ports:
      - 9093:9093
    volumes:
      - D:\code\compose-config\prometheus\alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - D:\code\compose-config\prometheus\template:/etc/prometheus/template
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    ports:
      - 9100:9100
    volumes:
      - D:\code\compose-config\prometheus\node-exporter:/host:ro,rslave
    command:
      - '--path.rootfs=/host'