version: "3.8"

services:
  com.demo.docker:
    build: ./docker
    restart: always
    container_name: com.demo.docker
    ports:
      - 8088:8088
    volumes:
      - D:\code\demo\win-compose\data\:/app/data
      - D:\code\demo\docker\logs\:/app/demo/logs