// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.2
// source: stream.proto

package stream

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ExampleService_ProcessBinaryData_FullMethodName = "/ExampleService/ProcessBinaryData"
)

// ExampleServiceClient is the client API for ExampleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExampleServiceClient interface {
	ProcessBinaryData(ctx context.Context, opts ...grpc.CallOption) (ExampleService_ProcessBinaryDataClient, error)
}

type exampleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExampleServiceClient(cc grpc.ClientConnInterface) ExampleServiceClient {
	return &exampleServiceClient{cc}
}

func (c *exampleServiceClient) ProcessBinaryData(ctx context.Context, opts ...grpc.CallOption) (ExampleService_ProcessBinaryDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &ExampleService_ServiceDesc.Streams[0], ExampleService_ProcessBinaryData_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &exampleServiceProcessBinaryDataClient{stream}
	return x, nil
}

type ExampleService_ProcessBinaryDataClient interface {
	Send(*BytesInput) error
	CloseAndRecv() (*BytesOutput, error)
	grpc.ClientStream
}

type exampleServiceProcessBinaryDataClient struct {
	grpc.ClientStream
}

func (x *exampleServiceProcessBinaryDataClient) Send(m *BytesInput) error {
	return x.ClientStream.SendMsg(m)
}

func (x *exampleServiceProcessBinaryDataClient) CloseAndRecv() (*BytesOutput, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(BytesOutput)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ExampleServiceServer is the server API for ExampleService service.
// All implementations must embed UnimplementedExampleServiceServer
// for forward compatibility
type ExampleServiceServer interface {
	ProcessBinaryData(ExampleService_ProcessBinaryDataServer) error
	mustEmbedUnimplementedExampleServiceServer()
}

// UnimplementedExampleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedExampleServiceServer struct {
}

func (UnimplementedExampleServiceServer) ProcessBinaryData(ExampleService_ProcessBinaryDataServer) error {
	return status.Errorf(codes.Unimplemented, "method ProcessBinaryData not implemented")
}
func (UnimplementedExampleServiceServer) mustEmbedUnimplementedExampleServiceServer() {}

// UnsafeExampleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExampleServiceServer will
// result in compilation errors.
type UnsafeExampleServiceServer interface {
	mustEmbedUnimplementedExampleServiceServer()
}

func RegisterExampleServiceServer(s grpc.ServiceRegistrar, srv ExampleServiceServer) {
	s.RegisterService(&ExampleService_ServiceDesc, srv)
}

func _ExampleService_ProcessBinaryData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExampleServiceServer).ProcessBinaryData(&exampleServiceProcessBinaryDataServer{stream})
}

type ExampleService_ProcessBinaryDataServer interface {
	SendAndClose(*BytesOutput) error
	Recv() (*BytesInput, error)
	grpc.ServerStream
}

type exampleServiceProcessBinaryDataServer struct {
	grpc.ServerStream
}

func (x *exampleServiceProcessBinaryDataServer) SendAndClose(m *BytesOutput) error {
	return x.ServerStream.SendMsg(m)
}

func (x *exampleServiceProcessBinaryDataServer) Recv() (*BytesInput, error) {
	m := new(BytesInput)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ExampleService_ServiceDesc is the grpc.ServiceDesc for ExampleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExampleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ExampleService",
	HandlerType: (*ExampleServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessBinaryData",
			Handler:       _ExampleService_ProcessBinaryData_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "stream.proto",
}
