// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package stream

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StreamHttpClient is the client API for StreamHttp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamHttpClient interface {
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (StreamHttp_UploadFileClient, error)
}

type streamHttpClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamHttpClient(cc grpc.ClientConnInterface) StreamHttpClient {
	return &streamHttpClient{cc}
}

func (c *streamHttpClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (StreamHttp_UploadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamHttp_ServiceDesc.Streams[0], "/StreamHttp/UploadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamHttpUploadFileClient{stream}
	return x, nil
}

type StreamHttp_UploadFileClient interface {
	Send(*FileChunk) error
	CloseAndRecv() (*emptypb.Empty, error)
	grpc.ClientStream
}

type streamHttpUploadFileClient struct {
	grpc.ClientStream
}

func (x *streamHttpUploadFileClient) Send(m *FileChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamHttpUploadFileClient) CloseAndRecv() (*emptypb.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(emptypb.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamHttpServer is the server API for StreamHttp service.
// All implementations must embed UnimplementedStreamHttpServer
// for forward compatibility
type StreamHttpServer interface {
	UploadFile(StreamHttp_UploadFileServer) error
	mustEmbedUnimplementedStreamHttpServer()
}

// UnimplementedStreamHttpServer must be embedded to have forward compatible implementations.
type UnimplementedStreamHttpServer struct {
}

func (UnimplementedStreamHttpServer) UploadFile(StreamHttp_UploadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedStreamHttpServer) mustEmbedUnimplementedStreamHttpServer() {}

// UnsafeStreamHttpServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamHttpServer will
// result in compilation errors.
type UnsafeStreamHttpServer interface {
	mustEmbedUnimplementedStreamHttpServer()
}

func RegisterStreamHttpServer(s grpc.ServiceRegistrar, srv StreamHttpServer) {
	s.RegisterService(&StreamHttp_ServiceDesc, srv)
}

func _StreamHttp_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamHttpServer).UploadFile(&streamHttpUploadFileServer{stream})
}

type StreamHttp_UploadFileServer interface {
	SendAndClose(*emptypb.Empty) error
	Recv() (*FileChunk, error)
	grpc.ServerStream
}

type streamHttpUploadFileServer struct {
	grpc.ServerStream
}

func (x *streamHttpUploadFileServer) SendAndClose(m *emptypb.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamHttpUploadFileServer) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamHttp_ServiceDesc is the grpc.ServiceDesc for StreamHttp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamHttp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "StreamHttp",
	HandlerType: (*StreamHttpServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFile",
			Handler:       _StreamHttp_UploadFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "stream.proto",
}
