// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package stream

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StreamHttpClient is the client API for StreamHttp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamHttpClient interface {
	UploadFile(ctx context.Context, in *FileChunk, opts ...grpc.CallOption) (*FileChunk, error)
}

type streamHttpClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamHttpClient(cc grpc.ClientConnInterface) StreamHttpClient {
	return &streamHttpClient{cc}
}

func (c *streamHttpClient) UploadFile(ctx context.Context, in *FileChunk, opts ...grpc.CallOption) (*FileChunk, error) {
	out := new(FileChunk)
	err := c.cc.Invoke(ctx, "/StreamHttp/UploadFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamHttpServer is the server API for StreamHttp service.
// All implementations must embed UnimplementedStreamHttpServer
// for forward compatibility
type StreamHttpServer interface {
	UploadFile(context.Context, *FileChunk) (*FileChunk, error)
	mustEmbedUnimplementedStreamHttpServer()
}

// UnimplementedStreamHttpServer must be embedded to have forward compatible implementations.
type UnimplementedStreamHttpServer struct {
}

func (UnimplementedStreamHttpServer) UploadFile(context.Context, *FileChunk) (*FileChunk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedStreamHttpServer) mustEmbedUnimplementedStreamHttpServer() {}

// UnsafeStreamHttpServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamHttpServer will
// result in compilation errors.
type UnsafeStreamHttpServer interface {
	mustEmbedUnimplementedStreamHttpServer()
}

func RegisterStreamHttpServer(s grpc.ServiceRegistrar, srv StreamHttpServer) {
	s.RegisterService(&StreamHttp_ServiceDesc, srv)
}

func _StreamHttp_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileChunk)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamHttpServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StreamHttp/UploadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamHttpServer).UploadFile(ctx, req.(*FileChunk))
	}
	return interceptor(ctx, in, info, handler)
}

// StreamHttp_ServiceDesc is the grpc.ServiceDesc for StreamHttp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamHttp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "StreamHttp",
	HandlerType: (*StreamHttpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadFile",
			Handler:    _StreamHttp_UploadFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stream.proto",
}
