global:
  scrape_interval: 60s
  
scrape_configs:
  - job_name: "com.ghs.gateway"
    static_configs:
      - targets: ["192.168.10.103:38101"]
      
  #- job_name: "com.ghs.alarm"
  #  static_configs:
  #    - targets: ["192.168.10.103:38401"]
      
rule_files:
  # 引入告警规则文件
  - "/etc/prometheus/rules/rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["192.168.10.103:9093"]