// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: p.proto

package p

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MethodId int32

const (
	MethodId_DATA_INIT   MethodId = 0
	MethodId_DATA_GET    MethodId = 1
	MethodId_DATA_UPDATE MethodId = 2
)

// Enum value maps for MethodId.
var (
	MethodId_name = map[int32]string{
		0: "DATA_INIT",
		1: "DATA_GET",
		2: "DATA_UPDATE",
	}
	MethodId_value = map[string]int32{
		"DATA_INIT":   0,
		"DATA_GET":    1,
		"DATA_UPDATE": 2,
	}
)

func (x MethodId) Enum() *MethodId {
	p := new(MethodId)
	*p = x
	return p
}

func (x MethodId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MethodId) Descriptor() protoreflect.EnumDescriptor {
	return file_p_proto_enumTypes[0].Descriptor()
}

func (MethodId) Type() protoreflect.EnumType {
	return &file_p_proto_enumTypes[0]
}

func (x MethodId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MethodId.Descriptor instead.
func (MethodId) EnumDescriptor() ([]byte, []int) {
	return file_p_proto_rawDescGZIP(), []int{0}
}

type WsData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MethodId  MethodId               `protobuf:"varint,1,opt,name=methodId,proto3,enum=MethodId" json:"methodId,omitempty"`
	Path      string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	FieldMask *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=fieldMask,proto3" json:"fieldMask,omitempty"`
	// Types that are assignable to Data:
	//	*WsData_Int32Data
	//	*WsData_FloatData
	//	*WsData_StringData
	//	*WsData_BoolData
	//	*WsData_BytesData
	Data isWsData_Data `protobuf_oneof:"data"`
	X    *XInfo        `protobuf:"bytes,9,opt,name=x,proto3" json:"x,omitempty"`
}

func (x *WsData) Reset() {
	*x = WsData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsData) ProtoMessage() {}

func (x *WsData) ProtoReflect() protoreflect.Message {
	mi := &file_p_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsData.ProtoReflect.Descriptor instead.
func (*WsData) Descriptor() ([]byte, []int) {
	return file_p_proto_rawDescGZIP(), []int{0}
}

func (x *WsData) GetMethodId() MethodId {
	if x != nil {
		return x.MethodId
	}
	return MethodId_DATA_INIT
}

func (x *WsData) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WsData) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

func (m *WsData) GetData() isWsData_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *WsData) GetInt32Data() int32 {
	if x, ok := x.GetData().(*WsData_Int32Data); ok {
		return x.Int32Data
	}
	return 0
}

func (x *WsData) GetFloatData() float32 {
	if x, ok := x.GetData().(*WsData_FloatData); ok {
		return x.FloatData
	}
	return 0
}

func (x *WsData) GetStringData() string {
	if x, ok := x.GetData().(*WsData_StringData); ok {
		return x.StringData
	}
	return ""
}

func (x *WsData) GetBoolData() bool {
	if x, ok := x.GetData().(*WsData_BoolData); ok {
		return x.BoolData
	}
	return false
}

func (x *WsData) GetBytesData() []byte {
	if x, ok := x.GetData().(*WsData_BytesData); ok {
		return x.BytesData
	}
	return nil
}

func (x *WsData) GetX() *XInfo {
	if x != nil {
		return x.X
	}
	return nil
}

type isWsData_Data interface {
	isWsData_Data()
}

type WsData_Int32Data struct {
	Int32Data int32 `protobuf:"varint,4,opt,name=int32Data,proto3,oneof"`
}

type WsData_FloatData struct {
	FloatData float32 `protobuf:"fixed32,5,opt,name=floatData,proto3,oneof"`
}

type WsData_StringData struct {
	StringData string `protobuf:"bytes,6,opt,name=stringData,proto3,oneof"`
}

type WsData_BoolData struct {
	BoolData bool `protobuf:"varint,7,opt,name=boolData,proto3,oneof"`
}

type WsData_BytesData struct {
	BytesData []byte `protobuf:"bytes,8,opt,name=bytesData,proto3,oneof"`
}

func (*WsData_Int32Data) isWsData_Data() {}

func (*WsData_FloatData) isWsData_Data() {}

func (*WsData_StringData) isWsData_Data() {}

func (*WsData_BoolData) isWsData_Data() {}

func (*WsData_BytesData) isWsData_Data() {}

type XInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code int32  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *XInfo) Reset() {
	*x = XInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XInfo) ProtoMessage() {}

func (x *XInfo) ProtoReflect() protoreflect.Message {
	mi := &file_p_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XInfo.ProtoReflect.Descriptor instead.
func (*XInfo) Descriptor() ([]byte, []int) {
	return file_p_proto_rawDescGZIP(), []int{1}
}

func (x *XInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *XInfo) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_p_proto protoreflect.FileDescriptor

var file_p_proto_rawDesc = []byte{
	0x0a, 0x07, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbb, 0x02, 0x0a, 0x06,
	0x57, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x49, 0x64, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x12, 0x38, 0x0a, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4d, 0x61, 0x73, 0x6b, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4d, 0x61, 0x73, 0x6b,
	0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x1e, 0x0a, 0x09, 0x69,
	0x6e, 0x74, 0x33, 0x32, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00,
	0x52, 0x09, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x09, 0x66,
	0x6c, 0x6f, 0x61, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00,
	0x52, 0x09, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x0a, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x0a, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a,
	0x08, 0x62, 0x6f, 0x6f, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x48,
	0x00, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x09, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00,
	0x52, 0x09, 0x62, 0x79, 0x74, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x01, 0x78,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x78, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x01,
	0x78, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2f, 0x0a, 0x05, 0x78, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x2a, 0x38, 0x0a, 0x08, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x49, 0x64, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x49,
	0x4e, 0x49, 0x54, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x47, 0x45,
	0x54, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x55, 0x50, 0x44, 0x41,
	0x54, 0x45, 0x10, 0x02, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2e, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_p_proto_rawDescOnce sync.Once
	file_p_proto_rawDescData = file_p_proto_rawDesc
)

func file_p_proto_rawDescGZIP() []byte {
	file_p_proto_rawDescOnce.Do(func() {
		file_p_proto_rawDescData = protoimpl.X.CompressGZIP(file_p_proto_rawDescData)
	})
	return file_p_proto_rawDescData
}

var file_p_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_p_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_p_proto_goTypes = []interface{}{
	(MethodId)(0),                 // 0: MethodId
	(*WsData)(nil),                // 1: WsData
	(*XInfo)(nil),                 // 2: xInfo
	(*fieldmaskpb.FieldMask)(nil), // 3: google.protobuf.FieldMask
}
var file_p_proto_depIdxs = []int32{
	0, // 0: WsData.methodId:type_name -> MethodId
	3, // 1: WsData.fieldMask:type_name -> google.protobuf.FieldMask
	2, // 2: WsData.x:type_name -> xInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_p_proto_init() }
func file_p_proto_init() {
	if File_p_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_p_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WsData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_p_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*WsData_Int32Data)(nil),
		(*WsData_FloatData)(nil),
		(*WsData_StringData)(nil),
		(*WsData_BoolData)(nil),
		(*WsData_BytesData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_p_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_p_proto_goTypes,
		DependencyIndexes: file_p_proto_depIdxs,
		EnumInfos:         file_p_proto_enumTypes,
		MessageInfos:      file_p_proto_msgTypes,
	}.Build()
	File_p_proto = out.File
	file_p_proto_rawDesc = nil
	file_p_proto_goTypes = nil
	file_p_proto_depIdxs = nil
}
