groups:
- name: alarm-rules
  rules:
  - alert: ServiceDown
    expr: up == 0
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: 'Service {{$labels.instance}} of job {{$labels.job}} is down'
      description: 'The service {{$labels.instance}} of job {{$labels.job}} has been down for more than 1 minute'
      resolved_summary: 'Service {{$labels.instance}} of job {{$labels.job}} is up'
      resolved_description: 'The service {{$labels.instance}} of job {{$labels.job}} has been up'
      
  - alert: ServiceDown
    expr: up == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: 'Service {{$labels.instance}} of job {{$labels.job}} is down'
      description: 'The service {{$labels.instance}} of job {{$labels.job}} has been down for more than 5 minute'
      resolved_summary: 'Service {{$labels.instance}} of job {{$labels.job}} is up'
      resolved_description: 'The service {{$labels.instance}} of job {{$labels.job}} has been up'
      
  - alert: ServiceDown
    expr: up == 0
    for: 10m
    labels:
      severity: page
    annotations:
      summary: 'Service {{$labels.instance}} of job {{$labels.job}} is down'
      description: 'The service {{$labels.instance}} of job {{$labels.job}} has been down for more than 10 minute'
      resolved_summary: 'Service {{$labels.instance}} of job {{$labels.job}} is up'
      resolved_description: 'The service {{$labels.instance}} of job {{$labels.job}} has been up'