// 协议类型

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.22.2
// source: study.proto

package study

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StudyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *StudyRequest) Reset() {
	*x = StudyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_study_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudyRequest) ProtoMessage() {}

func (x *StudyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_study_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudyRequest.ProtoReflect.Descriptor instead.
func (*StudyRequest) Descriptor() ([]byte, []int) {
	return file_study_proto_rawDescGZIP(), []int{0}
}

func (x *StudyRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type StudyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	List    []*Info `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *StudyResponse) Reset() {
	*x = StudyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_study_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudyResponse) ProtoMessage() {}

func (x *StudyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_study_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudyResponse.ProtoReflect.Descriptor instead.
func (*StudyResponse) Descriptor() ([]byte, []int) {
	return file_study_proto_rawDescGZIP(), []int{1}
}

func (x *StudyResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StudyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StudyResponse) GetList() []*Info {
	if x != nil {
		return x.List
	}
	return nil
}

type Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DevId string `protobuf:"bytes,1,opt,name=devId,proto3" json:"devId,omitempty"`
	Date  string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Time  string `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *Info) Reset() {
	*x = Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_study_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_study_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_study_proto_rawDescGZIP(), []int{2}
}

func (x *Info) GetDevId() string {
	if x != nil {
		return x.DevId
	}
	return ""
}

func (x *Info) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Info) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

var File_study_proto protoreflect.FileDescriptor

var file_study_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x74, 0x75, 0x64, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a, 0x0c, 0x53,
	0x74, 0x75, 0x64, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x58, 0x0a, 0x0d, 0x53, 0x74, 0x75, 0x64, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x19, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05,
	0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x44, 0x0a, 0x04, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x76, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x64, 0x65, 0x76, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x32, 0x49, 0x0a, 0x09, 0x53, 0x74, 0x75, 0x64, 0x79, 0x48, 0x74, 0x74, 0x70, 0x12, 0x3c,
	0x0a, 0x08, 0x53, 0x61, 0x79, 0x53, 0x74, 0x75, 0x64, 0x79, 0x12, 0x0d, 0x2e, 0x53, 0x74, 0x75,
	0x64, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x53, 0x74, 0x75, 0x64,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x0b, 0x22, 0x06, 0x2f, 0x73, 0x74, 0x75, 0x64, 0x79, 0x3a, 0x01, 0x2a, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x2f, 0x73, 0x74, 0x75, 0x64, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_study_proto_rawDescOnce sync.Once
	file_study_proto_rawDescData = file_study_proto_rawDesc
)

func file_study_proto_rawDescGZIP() []byte {
	file_study_proto_rawDescOnce.Do(func() {
		file_study_proto_rawDescData = protoimpl.X.CompressGZIP(file_study_proto_rawDescData)
	})
	return file_study_proto_rawDescData
}

var file_study_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_study_proto_goTypes = []interface{}{
	(*StudyRequest)(nil),  // 0: StudyRequest
	(*StudyResponse)(nil), // 1: StudyResponse
	(*Info)(nil),          // 2: Info
}
var file_study_proto_depIdxs = []int32{
	2, // 0: StudyResponse.list:type_name -> Info
	0, // 1: StudyHttp.SayStudy:input_type -> StudyRequest
	1, // 2: StudyHttp.SayStudy:output_type -> StudyResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_study_proto_init() }
func file_study_proto_init() {
	if File_study_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_study_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_study_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_study_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_study_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_study_proto_goTypes,
		DependencyIndexes: file_study_proto_depIdxs,
		MessageInfos:      file_study_proto_msgTypes,
	}.Build()
	File_study_proto = out.File
	file_study_proto_rawDesc = nil
	file_study_proto_goTypes = nil
	file_study_proto_depIdxs = nil
}
